services:
  api:
    container_name: identity-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  db:
    container_name: identity-db
    build: ./docker/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data

volumes:
  data: